spring:
    application:
        name: CloudBlog
    data:
        mongodb:
          ip: 172.19.0.2
          port: 27017
          db: cloudblog

server:
    port: 8080

logging:
    file: logs/${spring.application.name}.log

